### ISSUE TITLE
pnpm run -r build 命令报错

### ISSUE THREAD

**Issue by ztm0929** [cooderl/wewe-rss#1]
node版本号：v18.18.0
npm版本号：9.8.1
pnpm版本号：8.15.4

具体错误代码：
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  web@0.1.0 build: `next build`
Exit status 1

大佬，请求如何解决？

**Comment by cooderl** [comment]
是什么系统呢？windows还是linux

**Comment by ztm0929** [comment]
> 是什么系统呢？windows还是linux

抱歉遗漏了，是Windows 11 23H2 22631.3155

我的macOS其实也有类似的报错😂：
系统：14.4 Beta (23E5205c)
node：v21.6.2
npm：10.2.4
pnpm：8.15.4

我不太懂node.js，也许得等大佬的docker部署方案了～

**Comment by cooderl** [comment]
docker 部署按照这个试一下

https://github.com/cooderl/wewe-rss?tab=readme-ov-file#docker-compose-%E9%83%A8%E7%BD%B2

**Comment by cooderl** [comment]
前后端打包成一个镜像了，有问题再开issue
