### ISSUE TITLE
假开源吗? https://weread.111965.xyz 是什么服务? 这个项目强依赖这个接口?

### ISSUE THREAD

**Issue by eightHundreds** [cooderl/wewe-rss#11]
<img width="494" alt="image" src="https://github.com/cooderl/wewe-rss/assets/18695431/62e29599-31f2-4011-b31d-e25eec9e88f8">

**Comment by eightHundreds** [comment]
我发现它似乎把用户的token也转发到这个服务了.

**Comment by eightHundreds** [comment]
> 我发现它似乎把用户的token也转发到这个服务了.

你应该声明这个风险

**Comment by cooderl** [comment]
token是从这个服务生成的，只做请求转发。
绝大部分代码都开源了，为了避免争议，我改一下描述，加上风险声明。
感谢提醒。

**Comment by jtsang4** [comment]
@cooderl 这个服务后续可以改成自己部署吗？否则还是有点担心数据不安全

**Comment by phith0n** [comment]
> 为了确保本项目的持久运行，某些接口请求将通过weread.111965.xyz进行转发。请放心，该转发服务不会保存任何数据。

不懂为什么要做一个转发服务器，用户token为啥会走这个服务器？关于token这一点风险，能不能写到描述里？

**Comment by eightHundreds** [comment]
![Screenshot_2024-03-02-22-51-30-039_com tencent weread](https://github.com/cooderl/wewe-rss/assets/18695431/02b596e1-d5e0-4fd8-88c0-605415f9ba29)
我的小号，今天第一次用微信读书。但是却显示昨天有登录过

**Comment by eightHundreds** [comment]
我大概能猜到作者的实现方案，微信官方完全可以通过限制单台手机登录的微信号数量来解决这个漏洞。

**Comment by LakeishaKowalczyk** [comment]
@eightHundreds 
意思是 `https://weread.111965.xyz` 这个服务器会自行使用登录过的微信账号，用所有人的微信号分流？

即然开源能不能不要搞讳莫如深那一套

**Comment by eightHundreds** [comment]
> @eightHundreds 意思是 `https://weread.111965.xyz` 这个服务器会自行使用登录过的微信账号，用所有人的微信号分流？
> 
> 即然开源能不能不要搞讳莫如深那一套

理论上他是能做到的

**Comment by hawkproject** [comment]
placeholder
