### ISSUE TITLE
请问作者鼓励自发性宣传吗

### ISSUE THREAD

**Issue by DC1024** [cooderl/wewe-rss#119]
这段时间使用wewe-rss的体验很不错，也很想自发宣传分享，但毕竟是涉及公众号的项目，之前也有不少类似项目接口被禁止或无法使用，虽然很想分享，但难免有些纠结，想问问作者是否有这方面的忧虑，是鼓励宣传还是不鼓励呢

**Comment by cooderl** [comment]
没有想这么多，哈哈。

**Comment by DC1024** [comment]
> 没有想这么多，哈哈。

好的😂
