### ISSUE TITLE
请问定时更新的周期是多少，参数在哪里设置？

### ISSUE THREAD

**Issue by CaoZihang** [cooderl/wewe-rss#12]
如题，十分感谢^_^

**Comment by cooderl** [comment]
cron是 35 5,17 * * * 

早上和下午 5:35

目前只能改代码，还没有支持直接设置，我看看怎么支持

**Comment by CaoZihang** [comment]
十分感谢，这个项目帮了大忙！加油！

**Comment by cooderl** [comment]
1.5版本加上了 CRON_EXPRESSION  参数可以修改更新周期
具体可以看一下readme 
有问题可以再提issue
