### ISSUE TITLE
使用过程中遇到某些公众号链接不能正常添加

### ISSUE THREAD

**Issue by wllwang8** [cooderl/wewe-rss#121]
不能正常添加的公众号链接示例（比github主页展示的url更长）：
https://mp.weixin.qq.com/s?__biz=MzI5MzMxMTU1OQ==&mid=2247485558&idx=1&sn=ec291a3c1c1cff9d55977527358b5b78&chksm=ed2c2d08ca2fd3ede67e87a67cd333afbb53ba7419833e89a8623a72df1d8300d8fb3ca65da8&scene=126&sessionid=1713867745#/rd

添加失败的图片显示：
![image](https://github.com/cooderl/wewe-rss/assets/52489891/4f6ff5cf-b60d-4284-a862-331939224f91)

**Comment by cooderl** [comment]
要 https://mp.weixin.qq.com/s/xxx  这样的分享链接才可以
