### ISSUE TITLE
docker 部署 出现Unable to find image 'cooderl/wewe-rss:latest' locally

### ISSUE THREAD

**Issue by mitxmu** [cooderl/wewe-rss#129]
debian服务器上docker 部署 出现Unable to find image 'cooderl/wewe-rss:latest' locally，想问一下怎么解决

**Comment by iferencz** [comment]
拉取镜像
```
docker pull cooderl/wewe-rss:latest
```

**Comment by mitxmu** [comment]
> 拉取镜像
> 
> ```
> docker pull cooderl/wewe-rss:latest
> ```

谢谢，解决了

**Comment by Yakezhou** [comment]
拉取镜像显示：
latest: Pulling from cooderl/wewe-rss
4abcf2066143: Pulling fs layer
7231dd947546: Pulling fs layer
58ec58ffa356: Pulling fs layer
853d72f1314b: Waiting
93d086406339: Waiting
a16af8672fd2: Waiting
4f4fb700ef54: Waiting
3ce7c2ce7926: Waiting

**Comment by qrkapp** [comment]
遇到同样问题，请问怎么解决的？
