### ISSUE TITLE
添加公众号源时报错：Invalid prisma.account.findFirst()

### ISSUE THREAD

**Issue by TommyMerlin** [cooderl/wewe-rss#14]
登录正常、添加账号正常，在添加公众号源的时候报如下错：

请求路径：/trpc/platform.getMpInfo?batch=1
请求方法：POST
响应：
> "error": {
            "message": "Invalid `prisma.account.findFirst()` invocation:{  where: {    status: 1,    NOT: {      id: {        in: [          undefined          ~~~~~~~~~        ]      }    }  }}Invalid value for argument `in[0]`: Can not use `undefined` value within array. Use `null` or filter out `undefined` values.",
            "code": -32603,
            "data": {
                "code": "INTERNAL_SERVER_ERROR",
                "httpStatus": 500,
                "path": "platform.getMpInfo"
            }

请问可能是啥原因引起的，该如何修改。
感谢。

**Comment by cooderl** [comment]
拉一下最新镜像再试试

**Comment by TommyMerlin** [comment]
可以了，可以正常添加了。
