### ISSUE TITLE
输出 RSS 时报错 {"statusCode":500,"message":"Internal server error"}

### ISSUE THREAD

**Issue by xiaozhubin** [cooderl/wewe-rss#141]
看网页已经获取到文章了，但输出 RSS 时报错 {"statusCode":500,"message":"Internal server error"}。
重启容器能解决，但，不知道什么时候，又会报错。
版本： v2.3.0
部分日志内容如下：

> 2024-05-19T10:46:33.194571290Z,stderr,    at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1482
> 
> 2024-05-19T10:46:33.194526420Z,stderr,    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> 2024-05-19T10:46:33.194475689Z,stderr,    at h (/app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1210)
> 
> 2024-05-19T10:46:33.194433206Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:33.194392255Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.194352488Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.194310049Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.194267475Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.194226617Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:33.194170110Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:33.194130000Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.194059743Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.194015504Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.193970237Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.193929870Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:33.193885659Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:33.193845945Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.193804254Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.193760339Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.193717373Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.193674906Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:33.193632170Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:33.193592724Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.193552828Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.193510304Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.193464729Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.193425569Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:33.193382510Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:33.193342318Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.193301943Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.193258851Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.193212886Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.193162306Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:33.193122737Z,stderr,AggregateError: 
> 
> 2024-05-19T10:46:33.193076946Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388[39m
> 
> 2024-05-19T10:46:33.193035320Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.192995148Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.192952649Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.192910091Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.192871845Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:33.192826246Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:33.192783310Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.192742595Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.192694003Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.192651652Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.192612812Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:33.192569639Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:33.192530764Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.192491051Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.192447877Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.192405069Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.192366331Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:33.192323069Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:33.192279671Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.192238897Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.192195242Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.192136714Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.192097251Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:33.192047621Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:33.192000632Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:33.191952289Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:33.191836782Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:33.191767887Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:33.191669505Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:32.856902277Z,stderr,"[31m[Nest] 73  - [39m05/19/2024, 10:46:32 AM [31m  ERROR[39m [38;5;3m[ExceptionsHandler] [39m[31m
> "
> 2024-05-19T10:46:31.607419630Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:46:31 AM [32m    LOG[39m [38;5;3m[FeedsService] [39m[32mhandleGenerateFeed articles: 10[39m
> "
> 2024-05-19T10:46:31.591001563Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:46:31 AM [32m    LOG[39m [38;5;3m[FeedsController] [39m[32mMP_WXS_3078407632[39m
> "
> 2024-05-19T10:46:31.590256809Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:46:31 AM [32m    LOG[39m [38;5;3m[FeedsController] [39m[32mgetFeed: [39m
> "
> 2024-05-19T10:46:19.419485478Z,stderr,    at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1482
> 
> 2024-05-19T10:46:19.419438334Z,stderr,    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> 2024-05-19T10:46:19.419382000Z,stderr,    at h (/app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1210)
> 
> 2024-05-19T10:46:19.419339372Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:46:19.419296249Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:19.419255799Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:19.419212732Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:19.419153501Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:19.419114017Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:19.419076090Z,stderr,AggregateError: 
> 
> 2024-05-19T10:46:19.419022144Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388[39m
> 
> 2024-05-19T10:46:19.418979152Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:46:19.418932234Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:46:19.418884696Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:46:19.418825083Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:46:19.418773290Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:46:19.418551718Z,stderr,"[31m[Nest] 73  - [39m05/19/2024, 10:46:19 AM [31m  ERROR[39m [38;5;3m[ExceptionsHandler] [39m[31m
> "
> 2024-05-19T10:46:18.865127493Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:46:18 AM [32m    LOG[39m [38;5;3m[FeedsService] [39m[32mhandleGenerateFeed articles: 10[39m
> "
> 2024-05-19T10:46:18.849082166Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:46:18 AM [32m    LOG[39m [38;5;3m[FeedsController] [39m[32mMP_WXS_3240385070[39m
> "
> 2024-05-19T10:46:18.848495999Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:46:18 AM [32m    LOG[39m [38;5;3m[FeedsController] [39m[32mgetFeed: [39m
> "
> 2024-05-19T10:45:55.717900599Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:45:55 AM [32m    LOG[39m [38;5;3m[FeedsService] [39m[32mhandleGenerateFeed articles: 10[39m
> "
> 2024-05-19T10:45:55.700304862Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:45:55 AM [32m    LOG[39m [38;5;3m[FeedsController] [39m[32mMP_WXS_2392208130[39m
> "
> 2024-05-19T10:45:55.699209958Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:45:55 AM [32m    LOG[39m [38;5;3m[FeedsController] [39m[32mgetFeed: [39m
> "
> 2024-05-19T10:45:26.959013714Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:45:26 AM [32m    LOG[39m [38;5;3m[FeedsService] [39m[32mhandleGenerateFeed articles: 10[39m
> "
> 2024-05-19T10:45:26.934087393Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:45:26 AM [32m    LOG[39m [38;5;3m[FeedsController] [39m[32mMP_WXS_3861880711[39m
> "
> 2024-05-19T10:45:26.933416594Z,stdout,"[32m[Nest] 73  - [39m05/19/2024, 10:45:26 AM [32m    LOG[39m [38;5;3m[FeedsController] [39m[32mgetFeed: [39m
> "
> 2024-05-19T10:45:10.454272022Z,stderr,    at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1482
> 
> 2024-05-19T10:45:10.454222768Z,stderr,    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> 2024-05-19T10:45:10.454161647Z,stderr,    at h (/app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1210)
> 
> 2024-05-19T10:45:10.454110014Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388
> 
> 2024-05-19T10:45:10.454070072Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:45:10.454029615Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:45:10.453986894Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:45:10.453943795Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:45:10.453904288Z,stderr,    ECACHEFULL: Cache max keys amount exceeded
> 
> 2024-05-19T10:45:10.453866084Z,stderr,AggregateError: 
> 
> 2024-05-19T10:45:10.453811091Z,stderr,        at async /app/node_modules/.pnpm/@cjs-exporter+p-map@5.5.0/node_modules/@cjs-exporter/p-map/dist/index.js:5:1388[39m
> 
> 2024-05-19T10:45:10.453766224Z,stderr,        at async mapper (/app/dist/feeds/feeds.service.js:154:31)
> 
> 2024-05-19T10:45:10.453707187Z,stderr,        at FeedsService.tryGetContent (/app/dist/feeds/feeds.service.js:117:17)
> 
> 2024-05-19T10:45:10.453659495Z,stderr,        at NodeCache.set (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:412:23)
> 
> 2024-05-19T10:45:10.453597082Z,stderr,        at NodeCache._error (/app/node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:762:17)
> 
> 2024-05-19T10:45:10.453495979Z,stderr,    ECACHEFULL: Cache max keys amount exceeded

**Comment by cooderl** [comment]
请更新v2.3.1
