### ISSUE TITLE
Docker 部署数据库的方式需要小更新 mysql_native_password

### ISSUE THREAD

**Issue by ztm0929** [cooderl/wewe-rss#154]
[最新版本](https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html)的 MySQL 变动似乎会影响到数据库的启动：

Important Change: The deprecated mysql_native_password authentication plugin is now disabled by default. It can be enabled by starting MySQL with the new [--mysql-native-password=ON](https://dev.mysql.com/doc/refman/8.4/en/server-options.html#option_mysqld_mysql-native-password) server option, or by adding mysql_native_password=ON to the [mysqld] section of your MySQL configuration file.

**Comment by Li-Jack** [comment]
✔ app Pulled                                                                                                                                                                      167.3s
   ✔ bca4290a9639 Pull complete                                                                                                                                                      6.8s
   ✔ 7c2db5f7a6ab Pull complete                                                                                                                                                     18.4s
   ✔ 75a98a8f875a Pull complete                                                                                                                                                     18.5s
   ✔ 83735e3938ad Pull complete                                                                                                                                                     18.5s
   ✔ 5a93800f0645 Pull complete                                                                                                                                                     18.7s
   ✔ f51f4ec71604 Pull complete                                                                                                                                                     22.8s
   ✔ 4f4fb700ef54 Pull complete                                                                                                                                                     22.8s
   ✔ 725c3d485e00 Pull complete                                                                                                                                                     22.9s
 ✔ db Pulled                                                                                                                                                                        89.9s
   ✔ 3c4da62cd991 Pull complete                                                                                                                                                     18.8s
   ✔ 6246d8c92d7f Pull complete                                                                                                                                                     18.9s
   ✔ 64e7eb422142 Pull complete                                                                                                                                                     18.9s
   ✔ f787785dc518 Pull complete                                                                                                                                                     19.0s
   ✔ 7585e10db184 Pull complete                                                                                                                                                     19.0s
   ✔ c69999011c03 Pull complete                                                                                                                                                     19.0s
   ✔ 1142f05d9006 Pull complete                                                                                                                                                     19.5s
   ✔ d598a5053b5c Pull complete                                                                                                                                                     19.6s
   ✔ 3de4462059cc Pull complete                                                                                                                                                     30.0s
   ✔ cca926667410 Pull complete                                                                                                                                                     30.0s
[+] Running 4/4
 ✔ Network werss_default   Created                                                                                                                                                   0.0s
 ✔ Volume "werss_db_data"  Created                                                                                                                                                   0.0s
 ✘ Container werss-db-1    Error                                                                                                                                                     3.7s
 ✔ Container werss-app-1   Created                                                                                                                                                   0.0s
dependency failed to start: container werss-db-1 exited (1)

这样的报错，要怎么处理下

**Comment by ginobefun** [comment]
需要把 docker-compose.yaml 的 这一行进行替换：

command: --default-authentication-plugin=mysql_native_password
修改为
command: --mysql-native-password=ON

**Comment by Cyiming** [comment]
> 需要把 docker-compose.yaml 的 这一行进行替换：
> 
> command: --default-authentication-plugin=mysql_native_password 修改为 command: --mysql-native-password=ON

请问无论旧的还是新的 都提示 怎么办呢

root@VM-8-8-debian:~/data/docker_data/wewe-rss# docker-compose up -d
[+] Running 1/2
 ⠿ Container wewe-rss-db-1   Waiting                                                                                                                                                                                                       6.4s
 ⠿ Container wewe-rss-app-1  Recreated                                                                                                                                                                                                     0.1s
container for service "db" is unhealthy
