### ISSUE TITLE
提示我“请求失败! Load failed”

### ISSUE THREAD

**Issue by xiaowuleyi** [cooderl/wewe-rss#16]
<img width="398" alt="image" src="https://github.com/cooderl/wewe-rss/assets/102008938/b15cc58c-d6d7-444a-8c06-bd2e5c458ae0">
不好意思，刚开始学会部署，能否咨询一下，大概哪里的问题吗？谢谢啦，打扰。

**Comment by ApusYe** [comment]
您好！遇到了同样的问题，请问是怎么解决的？ @xiaowuleyi

**Comment by ApusYe** [comment]
按[群晖NAS_docker部署 弹出failed to fetch · Issue #68 · cooderl/wewe-rss](https://github.com/cooderl/wewe-rss/issues/68)的回复，注释掉`SERVER_ORIGIN_URL`，解决了
