### ISSUE TITLE
fulltext全文拉取不到了

### ISSUE THREAD

**Issue by lin1005q** [cooderl/wewe-rss#166]
今天发现，新更新的文章全文拉不到了

**Comment by cooderl** [comment]
看一下后端的日志，有没有报错信息

**Comment by ApusYe** [comment]
我用群晖NAS上的docker搭建的服务端，也出现了全文拉取不到的问题——RSS阅读器能收到文章，但打开是一片空白。查docker后台，看到有一串的`getMpArticles  error`。详细的日志见附件，感谢开发者！！！
[wewe-rss_app_1.csv](https://github.com/user-attachments/files/15781055/wewe-rss_app_1.csv)

**Comment by Teda9** [comment]
获取不到全文 问题+1
https://ww.789800.xyz/feeds/MP_WXS_2398768042.atom
预览情况。
![image](https://github.com/cooderl/wewe-rss/assets/133856115/1ece0578-d1ed-449e-a76b-1ce43aef6df5)
atom链接情况
![image](https://github.com/cooderl/wewe-rss/assets/133856115/69f40ce5-6d87-45e3-84e6-9626360dac15)
容器日志
![image](https://github.com/cooderl/wewe-rss/assets/133856115/c7f2feb6-6f99-4d2e-bcad-02d8e584009c)

**Comment by lin1005q** [comment]
> 获取不到全文 问题+1 https://ww.789800.xyz/feeds/MP_WXS_2398768042.atom 预览情况。 ![image](https://private-user-images.githubusercontent.com/133856115/339632683-1ece0578-d1ed-449e-a76b-1ce43aef6df5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTI4MzAsIm5iZiI6MTcxOTgxMjUzMCwicGF0aCI6Ii8xMzM4NTYxMTUvMzM5NjMyNjgzLTFlY2UwNTc4LWQxZWQtNDQ5ZS1hNzZiLTFjZTQzYWVmNmRmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNTQyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzlkY2I4NDE3YWQ2Y2Q1ZDU1YjM1YTQyYjhiZDBhMDRhMzc2ZWQwOTk4NmUwY2Q5YzI1MjViYTE2ZTAxNTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oBshvVYMJtg49l1SXT3O9_55YfkXqvsDfhjz972JgZE) atom链接情况 ![image](https://private-user-images.githubusercontent.com/133856115/339632899-69f40ce5-6d87-45e3-84e6-9626360dac15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTI4MzAsIm5iZiI6MTcxOTgxMjUzMCwicGF0aCI6Ii8xMzM4NTYxMTUvMzM5NjMyODk5LTY5ZjQwY2U1LTZkODctNDVlMy04NGU2LTk2MjYzNjBkYWMxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNTQyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWE1ZDFkNGZlN2ZjZDEyODUwYzZkMGE3ZTZjMzg2MjhhNDQxMzgzMzc5NGM2NDE4YTg1ZDBiNDMwZjQxOGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dhhNXTRCLsWBqiJYIGelhgn3S_FYykieUIMqtAmATP4) 容器日志 ![image](https://private-user-images.githubusercontent.com/133856115/339633074-c7f2feb6-6f99-4d2e-bcad-02d8e584009c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTI4MzAsIm5iZiI6MTcxOTgxMjUzMCwicGF0aCI6Ii8xMzM4NTYxMTUvMzM5NjMzMDc0LWM3ZjJmZWI2LTZmOTktNGQyZS1iY2FkLTAyZDhlNTg0MDA5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNTQyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzMwZjNjZWJjZjdjMzUyZWM0MzMwZGY0YmI2ZGJkMzczNGNjZmY1YTBmOTFhZmQ1NmE1ZTQ3N2IxOGE3NDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d0dY8LRj1ImE8DON4tLCrE6lr4n2p1vp6tNGH_Jo5o0)

我也发现了 内容其实已经采集到了 是因为样式的原因 看不到了。这块主要涉及这块的代码。 不是搞前端的 debug比较麻烦

<img width="741" alt="image" src="https://github.com/cooderl/wewe-rss/assets/15811933/6adfef1a-90af-4cec-8f3f-f3ed9de250d0">
