### ISSUE TITLE
need AuthCode 这个怎么处理呀

### ISSUE THREAD

**Issue by JackyKen** [cooderl/wewe-rss#170]
![image](https://github.com/cooderl/wewe-rss/assets/9691831/9243710c-19f8-4437-abc7-02d272bdb03e)

**Comment by coolcoolron** [comment]
这个是不是随意更改，在配置的时候，目前看配置的时候写的123567

**Comment by coolcoolron** [comment]
试了下，部署的时候，更改默认的authcode的值，登录的时候，填入自己设置的值就可以了

**Comment by JackyKen** [comment]
谢谢，123567 搞定。

**Comment by JackyKen** [comment]
done
