### ISSUE TITLE
运行 wewe-rss-sqlite 镜像报错

### ISSUE THREAD

**Issue by TommyMerlin** [cooderl/wewe-rss#18]
使用的是默认的 docker-compose.sqlite.yml
运行报错日志：
![image](https://github.com/cooderl/wewe-rss/assets/32566324/eb59fc1a-24c3-4aaf-beea-e41a2e6fe977)

**Comment by TommyMerlin** [comment]
docker-compose文件：

```
environment:
      # 数据库连接地址
      - DATABASE_URL="file:../data/wewe-rss.db"

**Comment by Nakolu** [comment]
fixed at https://github.com/cooderl/wewe-rss/pull/19

**Comment by TommyMerlin** [comment]
可以，修改完docker-compose文件就可以了。
```yml
environment:
      # 数据库连接地址
      - DATABASE_URL=file:"../data/wewe-rss.db"
      - DATABASE_TYPE="sqlite"

**Comment by cooderl** [comment]
所以是改了哪里呢
