### ISSUE TITLE
添加微信号提示以下错误

### ISSUE THREAD

**Issue by waxnx** [cooderl/wewe-rss#181]
请求失败！
Request failed with status code 500

请求失败！
getaddrinfo EAI_AGAIN weread.111965.xyz

**Comment by javaDreamDeer** [comment]
我也是，今天才出现的错误，微信号登录二维码加载失败 AxiosError: Request failed with status code 500

**Comment by le0zh0u** [comment]
+1，看起来是转发服务那里的异常，等待下后续

**Comment by kobolibra** [comment]
今天是不是都无法更新了？

**Comment by frankieyue96** [comment]
+1

**Comment by Qiu12591** [comment]
+1 我也遇到了这个问题，换了不同服务器依然存在该问题

**Comment by huifanww87** [comment]
+1 我也遇到了这个问题，今天早上还是存在

**Comment by mxx1111** [comment]
我也是，早上发简报发了个昨天的，才发现可能是出问题了，上来一看，报错3008，换了个服务器和数据库也是一样的

**Comment by mytoolsAI** [comment]
我也是同样的问题

**Comment by xinmans** [comment]
+1

**Comment by cooderl** [comment]
好了

**Comment by Nickszy** [comment]
3008报错，又出现了
![image](https://github.com/user-attachments/assets/d7bbc13c-e562-4c3e-ac3f-1794d5e2510e)

**Comment by le0zh0u** [comment]
我也出现了/捂脸

**Comment by Crush-RY** [comment]
我也出现了这个问题
