### ISSUE TITLE
现在是不是用不了了，一直连接不上

### ISSUE THREAD

**Issue by mytoolsAI** [cooderl/wewe-rss#184]
今天发现没有更新，之前也有出现过，重新添加读书帐号就可以，但这次删除帐号后就一直添加不了，如图？

请问大神怎么解决？
![image](https://github.com/cooderl/wewe-rss/assets/171247761/b61563f7-0c8b-4a0b-a83c-a5dee9b32a17)

**Comment by le0zh0u** [comment]
应该都是同一个问题导致，需要等大佬处理了
https://github.com/cooderl/wewe-rss/issues/181

**Comment by cooderl** [comment]
好了

**Comment by langxuelang** [comment]
还是报这个500的错，是需要重新拉取新代码部署吗

**Comment by langxuelang** [comment]
@cooderl ，今天还是遇到这个问题。

日志中显示：
 LOG [TrpcService] error: 
[Nest] 70  - 06/29/2024, 1:24:42 PM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 70  - 06/29/2024, 1:24:42 PM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008


<img width="1292" alt="image" src="https://github.com/cooderl/wewe-rss/assets/1763538/16aaeea6-ad76-4f78-b464-1c441bcdfd0d">

**Comment by Luciatl** [comment]
@cooderl , 同，刚刚部署也遇到这个问题，日志记录同上

trpc/platform.createLoginUrl?batch=1 的请求报错

[
    {
        "error": {
            "message": "Request failed with status code 500",
            "code": -32603,
            "data": {
                "code": "INTERNAL_SERVER_ERROR",
                "httpStatus": 500,
                "path": "platform.createLoginUrl"
            }
        }
    }
]

**Comment by KingStoning** [comment]
亲爱的 @cooderl ，您好，我也出现了相同的问题，我查看日志发现也是这两天的问题，但是今天才发现。请问是否可以解决呢？还是这是腾讯的新机制？
很抱歉打扰到了您

> 好了
