### ISSUE TITLE
weread.111965.xyz 这个服务能否放开。这几天的大面积故障

### ISSUE THREAD

**Issue by bravet** [cooderl/wewe-rss#185]
RT.

感谢！

**Comment by mxx1111** [comment]
今天又开始了500啦，建议这个域名可以用户自己配置，或者有没有别的办法不走这个域名这里，哈哈哈

**Comment by frankieyue96** [comment]
same 刚好没一天🤣

**Comment by Luciatl** [comment]
same 目前还是500

**Comment by KingStoning** [comment]
哈哈，我的也是500

**Comment by Nickszy** [comment]
<img width="651" alt="image" src="https://github.com/cooderl/wewe-rss/assets/29924966/54a596d3-ffb0-4dfd-8103-4b5bb564264b">
有几天了，这个个是啥服务啊，服务器在外面么

**Comment by mrzhu666** [comment]
添加公众号报错

![image](https://github.com/cooderl/wewe-rss/assets/47910447/84453668-5687-4a6f-be1f-a284d23b25de)

**Comment by KINAXNG** [comment]
支持

**Comment by Juzi-xyhao** [comment]
现在可以了，不报错

**Comment by cooderl** [comment]
绝大部分人没有部署条件，另外放开可能会让这个方案失效。

**Comment by Nickszy** [comment]
那就希望楼主加强一下 服务的可靠性，开放赞助也可以
