### ISSUE TITLE
AssertionError [ERR_ASSERTION]: protocol mismatch  无法添加用户  v2.3.1

### ISSUE THREAD

**Issue by cangshantiannan** [cooderl/wewe-rss#189]
![image](https://github.com/cooderl/wewe-rss/assets/17872477/be9cc41e-3b77-444e-96ef-50be68287485)
docker 部署后无法添加账号

**Comment by cangshantiannan** [comment]
![image](https://github.com/cooderl/wewe-rss/assets/17872477/9c3f14db-3e9f-43d7-9bdb-104cb14e7523)
![image](https://github.com/cooderl/wewe-rss/assets/17872477/3005dd1a-ddbe-4bf1-998c-c3e81000837d)

**Comment by agczsz** [comment]
好像接口炸了

**Comment by cangshantiannan** [comment]
这个大家有遇见过吗

**Comment by le0zh0u** [comment]
我这正常的。尝试重新部署一下。

**Comment by le0zh0u** [comment]
最好有服务器里的报错消息
