### ISSUE TITLE
如何生成rss格式的订阅链接

### ISSUE THREAD

**Issue by u2003** [cooderl/wewe-rss#193]
![CleanShot_2024-07-03_223409@2x](https://github.com/cooderl/wewe-rss/assets/84957135/64b3c100-9d17-4611-a95f-5bcea00e2cb1)
如图，点击rss之后获得的一直都是atom链接。但我需要的是rss格式的订阅链接，github上介绍说支持rss、atom、json格式，我想请问如何是个rss格式的订阅链接呢，感谢！

**Comment by ztm0929** [comment]
@u2003 可以直接修改后缀

http://localhost:4000/feeds/all.atom
http://localhost:4000/feeds/all.rss

**Comment by u2003** [comment]
好的，感谢！

**Comment by 12qweas** [comment]
您好，我导出rss链接（类似http://localhost:4000/feeds/xxxxx.atom），但是在folo其他rss软件无法识别到是为什么，以及我该怎么做？谢谢您！
