### ISSUE TITLE
127.0.0.1：3008无法链接

### ISSUE THREAD

**Issue by dadaomamao** [cooderl/wewe-rss#196]
[Nest] 66  - 07/12/2024, 3:01:15 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:01:15 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:15 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:01:15 AM   ERROR [TrpcService] retry(1) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:01:15 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:15 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:01:15 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:01:19 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:01:19 AM   ERROR [TrpcService] retry(2) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:01:19 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:19 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:01:19 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:19 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:01:19 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:01:22 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:01:22 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:22 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:01:22 AM   ERROR [TrpcService] retry(3) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:01:22 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:22 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:01:22 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:01:26 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:01:26 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:26 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:01:26 AM   ERROR [TrpcService] retry(4) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:01:26 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:32 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:01:32 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:01:36 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:01:36 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:36 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:01:36 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:01:36 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:01:36 AM   ERROR [TrpcService] retry(1) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:01:36 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:38 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:01:38 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:01:39 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:01:39 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:39 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:01:39 AM   ERROR [TrpcService] retry(2) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:01:39 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:39 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:01:39 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:01:43 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:01:43 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:43 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:01:43 AM   ERROR [TrpcService] retry(3) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:01:43 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:43 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:01:43 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:01:46 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:01:46 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:46 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:01:46 AM   ERROR [TrpcService] retry(4) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:01:46 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:01:51 AM     LOG [FeedsController] getFeed: 
[Nest] 66  - 07/12/2024, 3:01:51 AM     LOG [FeedsController] MP_WXS_3274365552
[Nest] 66  - 07/12/2024, 3:01:51 AM     LOG [FeedsService] handleGenerateFeed articles: 10
[Nest] 66  - 07/12/2024, 3:05:02 AM     LOG [FeedsController] getFeed: 
[Nest] 66  - 07/12/2024, 3:05:02 AM     LOG [FeedsController] MP_WXS_3270216743
[Nest] 66  - 07/12/2024, 3:05:02 AM     LOG [FeedsService] handleGenerateFeed articles: 10
[Nest] 66  - 07/12/2024, 3:06:13 AM     LOG [FeedsController] getFeed: 
[Nest] 66  - 07/12/2024, 3:06:13 AM     LOG [FeedsController] MP_WXS_3861528564
[Nest] 66  - 07/12/2024, 3:06:13 AM     LOG [FeedsService] handleGenerateFeed articles: 10
[Nest] 66  - 07/12/2024, 3:10:21 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:10:21 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:10:25 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:10:25 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:10:25 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:10:25 AM   ERROR [TrpcService] retry(1) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:10:25 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:10:25 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:10:25 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:10:27 AM     LOG [FeedsController] getFeed: 
[Nest] 66  - 07/12/2024, 3:10:27 AM     LOG [FeedsController] MP_WXS_3545621847
[Nest] 66  - 07/12/2024, 3:10:27 AM     LOG [FeedsService] handleGenerateFeed articles: 10
[Nest] 66  - 07/12/2024, 3:10:28 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:10:28 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:10:28 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:10:28 AM   ERROR [TrpcService] retry(2) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:10:28 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:10:28 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:10:28 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:10:32 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:10:32 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:10:32 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:10:32 AM   ERROR [TrpcService] retry(3) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:10:32 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:10:32 AM   DEBUG [TrpcService] disabledAccounts: 
[Nest] 66  - 07/12/2024, 3:10:32 AM   DEBUG [TrpcService] Object:
[]

[Nest] 66  - 07/12/2024, 3:10:35 AM     LOG [TrpcService] error: 
[Nest] 66  - 07/12/2024, 3:10:35 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:10:35 AM   ERROR [TrpcService] Can't handle this error: 
connect ECONNREFUSED 127.0.0.1:3008
[Nest] 66  - 07/12/2024, 3:10:35 AM   ERROR [TrpcService] retry(4) getMpArticles  error: 
[Nest] 66  - 07/12/2024, 3:10:35 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 66  - 07/12/2024, 3:11:49 AM     LOG [FeedsController] getFeed: 
[Nest] 66  - 07/12/2024, 3:11:49 AM     LOG [FeedsController] MP_WXS_3015084009
[Nest] 66  - 07/12/2024, 3:11:49 AM     LOG [FeedsService] handleGenerateFeed articles: 10
翻了一下之前其他人的报错，似乎这个报错一直再出现。无法更新 手动更新也报Request failed with status code 500错误，无法添加账号
![624](https://github.com/user-attachments/assets/7f61b7d8-151c-4110-aedf-f41ef75d60c5)
已经尝试重启服务器，阿里云成都服务器 部署方式 docker-compose.sqlite.yml

**Comment by lihuibng** [comment]
same

**Comment by le0zh0u** [comment]
这个需要等作者处理下中转服务

**Comment by buertang** [comment]
> 这个需要等作者处理下中转服务

大概多久会处理好呀，感觉用一次就这样一次。刚部署上，可能运气太好了。

**Comment by gaoyajun01** [comment]
@cooderl 作者好，能告知中转服务是怎么搭建的？我可以自己搭建一个，非常感谢。

**Comment by gaoyajun01** [comment]
同样的问题，恳切的盼望能早日解决。

**Comment by dadaomamao** [comment]
如果可以，我也想自己搭建中转服务。

**Comment by le0zh0u** [comment]
这个问题作者已经迁移服务器解决了，可以关了。

**Comment by lihuibng** [comment]
这个问题 又出现了

**Comment by gaoyajun01** [comment]
@cooderl 作者好，能建个微信群方便沟通或者分享下怎么自己搭建转发服务。

**Comment by cao-gift** [comment]
> 这个问题作者已经迁移服务器解决了，可以关了。

又不行了。
