### ISSUE TITLE
添加读书账户：500 Internal Server Error

### ISSUE THREAD

**Issue by JadePureOne** [cooderl/wewe-rss#197]
wewerss-app-1  | Prisma schema loaded from prisma/schema.prisma
wewerss-app-1  | Datasource "db": SQLite database "wewe-rss.db" at "file:../data/wewe-rss.db"
wewerss-app-1  | 
wewerss-app-1  | SQLite database wewe-rss.db created at file:../data/wewe-rss.db
wewerss-app-1  | 
wewerss-app-1  | 1 migration found in prisma/migrations
wewerss-app-1  | 
wewerss-app-1  | Applying migration `20240301104100_init`
wewerss-app-1  | 
wewerss-app-1  | The following migration(s) have been applied:
wewerss-app-1  | 
wewerss-app-1  | migrations/
wewerss-app-1  |   └─ 20240301104100_init/
wewerss-app-1  |     └─ migration.sql
wewerss-app-1  |       
wewerss-app-1  | All migrations have been successfully applied.
wewerss-app-1  | npm notice 
wewerss-app-1  | npm notice New minor version of npm available! 10.5.2 -> 10.8.2
wewerss-app-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.2>
wewerss-app-1  | npm notice Run `npm install -g npm@10.8.2` to update!
wewerss-app-1  | npm notice 
wewerss-app-1  | CRON_EXPRESSION:  undefined
wewerss-app-1  | appVersion: v2.3.1
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [NestFactory] Starting Nest application...
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] PrismaModule dependencies initialized +34ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] ThrottlerModule dependencies initialized +18ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] TrpcModule dependencies initialized +0ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] AppModule dependencies initialized +2ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [InstanceLoader] FeedsModule dependencies initialized +0ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [RoutesResolver] AppController {/}: +15ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [RouterExplorer] Mapped {/, GET} route +4ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [RouterExplorer] Mapped {/robots.txt, GET} route +0ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [RouterExplorer] Mapped {/favicon.ico, GET} route +1ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [RouterExplorer] Mapped {/dash*, GET} route +1ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [RoutesResolver] FeedsController {/feeds}: +0ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [RouterExplorer] Mapped {/feeds, GET} route +0ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [RouterExplorer] Mapped {/feeds/all.(json|rss|atom), GET} route +2ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [RouterExplorer] Mapped {/feeds/:feed, GET} route +1ms
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:35:44 AM     LOG [NestApplication] Nest application successfully started +57ms
wewerss-app-1  | Server is running at http://0.0.0.0:4000
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:36:05 AM   DEBUG [TrpcService] disabledAccounts: 
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:36:05 AM   DEBUG [TrpcService] Object:
wewerss-app-1  | []
wewerss-app-1  | 
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:36:08 AM     LOG [TrpcService] error: 
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:36:08 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
wewerss-app-1  | [Nest] 91  - 07/12/2024, 10:36:08 AM   ERROR [TrpcService] Can't handle this error: 
wewerss-app-1  | connect ECONNREFUSED 127.0.0.1:3008

**Comment by gaoyajun01** [comment]
@cooderl  您好，能加下您的微信吗？

**Comment by yanganan** [comment]
我也是添加账号抱500错误

**Comment by gaoyajun01** [comment]
我是正常用着，突然发现中转服务不可用了，没辙

**Comment by JadePureOne** [comment]
> 我是正常用着，突然发现中转服务不可用了，没辙

这么不稳定，看了圈Issue有很多这种情况

**Comment by le0zh0u** [comment]
https://github.com/cooderl/wewe-rss/issues/196
一个问题。
之前还是挺稳的。

**Comment by le0zh0u** [comment]
这个问题作者已经迁移服务器解决了，可以关了。
