### ISSUE TITLE
更新提示500错误

### ISSUE THREAD

**Issue by langxuelang** [cooderl/wewe-rss#199]
AxiosError: Request failed with status code 500
[Nest] 70  - 07/14/2024, 2:23:57 AM   ERROR [TrpcService] Can't handle this error: 

上一次就是这样了，估计是中转服务又挂了

**Comment by le0zh0u** [comment]
https://github.com/cooderl/wewe-rss/issues/196
应该是相同的问题

**Comment by le0zh0u** [comment]
这个问题作者已经迁移服务器解决了，可以关了。
