### ISSUE TITLE
使用 docker 部署报错

### ISSUE THREAD

**Issue by 98zi** [cooderl/wewe-rss#2]
https://github.com/cooderl/wewe-rss?tab=readme-ov-file#docker-%E5%91%BD%E4%BB%A4%E5%90%AF%E5%8A%A8

按照这种方式部署，修改了 2、3中的 SERVER_ORIGIN_URL 参数为自己的服务器ip+端口。

网页一刷新，server 服务就挂了，重启后再刷新网页还是挂掉。

![image](https://github.com/cooderl/wewe-rss/assets/65840178/96974680-b119-45c9-acd4-060a9e8dd3c3)

**Comment by cooderl** [comment]
可以尝试一下最新的镜像，应该是修复了。

**Comment by 98zi** [comment]
可以了，这个项目很厉害

**Comment by cooderl** [comment]
很多功能还没有加上，需要删除啥？

**Comment by 98zi** [comment]
> 很多功能还没有加上，需要删除啥？

比如说订阅了某个公众号，过段时间想取消订阅，没有删除功能

**Comment by AmintaCCCP** [comment]
希望能搞到一个容器里🙏

**Comment by cooderl** [comment]
> 希望能搞到一个容器里🙏

嗯嗯，nextjs问题太多了，我把它换成react跟nestjs打到一个包里面

**Comment by xiaozhubin** [comment]
我的也报错了。数据库是使用的nas自带的mysql，数据库创建什么的都正常，网页也能打开，但是添加账号的时候，一直转圈，打不开。
![image](https://github.com/cooderl/wewe-rss/assets/33818355/10c7f0f8-5dfe-4c08-a096-24a5bd86fc09)

**Comment by cooderl** [comment]
> > 很多功能还没有加上，需要删除啥？
> 
> 比如说订阅了某个公众号，过段时间想取消订阅，没有删除功能

加上删除功能了

**Comment by cooderl** [comment]
> 希望能搞到一个容器里🙏

移除nextjs了，现在是在一个容器里面了
