### ISSUE TITLE
暂无可用读书账号!

### ISSUE THREAD

**Issue by ivanlee1999** [cooderl/wewe-rss#20]
添加了几个公众号之后就提示 暂无可用读书账号!
尝试过删除读书账号重新添加， 还是不行
![CleanShot 2024-03-01 at 23 55 33@2x](https://github.com/cooderl/wewe-rss/assets/73640368/1a5aaa76-8bf3-4459-a62f-85576e15c287)

**Comment by cooderl** [comment]
可能被疯狂了。是不是一下子添加了很多个公众号？如果是的话换个微信号，或者等明天再试试
