### ISSUE TITLE
【建议】增加基于标题的关键词过滤功能

### ISSUE THREAD

**Issue by wyn-ying** [cooderl/wewe-rss#200]
背景：订阅的公众号发布内容太多，订阅者只对其中一部分主题的内容感兴趣。

诉求：是否可以在feeds之外增加一个新频道，允许配置一些关键词，并对公众号发布文章的标题进行关键词过滤，只保留包含关键词的文章。

希望作者可以考虑，谢谢！

**Comment by ztm0929** [comment]
想法挺好的，不过这或许也是阅读器的功能，可以试试看阅读器里的筛选（我使用的是 [Fluent Reader](https://github.com/yang991178/fluent-reader)）。额外增加并非RSS源处理的功能比较耗费精力。

参考 #48 

![image](https://github.com/user-attachments/assets/83e83b75-c8fd-450b-bfaf-2bb39d4c416e)

**Comment by wyn-ying** [comment]
根据我自己的需求魔改了一个版本，增加两个功能

1. 支持通过title_include和title_exclude对标题进行筛选。用法示例：
> {{ORIGIN_URL}}/feeds/filter.atom?title_include=张三
> {{ORIGIN_URL}}/feeds/MP_WXS_123.json?limit=30&title_include=张三|李四|王五&title_exclude=张三丰|赵六
2. 支持通过update=true触发更新某个指定feed（实时返回未更新的articles，获取更新后的articles需去掉update参数再请求一次）。用法示例：
> {{ORIGIN_URL}}/feeds/MP_WXS_123.rss?update=true

有类似的需求可以参考 [compare](https://github.com/cooderl/wewe-rss/compare/main...wyn-ying:wewe-rss:wyn)

**Comment by wyn-ying** [comment]
> 根据我自己的需求魔改了一个版本，增加两个功能
> 
> 1. 支持通过title_include和title_exclude对标题进行筛选。用法示例：
> 
> > {{ORIGIN_URL}}/feeds/filter.atom?title_include=张三
> > {{ORIGIN_URL}}/feeds/MP_WXS_123.json?limit=30&title_include=张三|李四|王五&title_exclude=张三丰|赵六
> 
> 2. 支持通过update=true触发更新某个指定feed（实时返回未更新的articles，获取更新后的articles需去掉update参数再请求一次）。用法示例：
> 
> > {{ORIGIN_URL}}/feeds/MP_WXS_123.rss?update=true
> 
> 有类似的需求可以参考 [compare](https://github.com/cooderl/wewe-rss/compare/v2.3.1...wyn-ying:wewe-rss:wyn)

做了部分接口上的调整，已提[PR](https://github.com/cooderl/wewe-rss/pull/216)
