### ISSUE TITLE
添加账号显示 Request failed with status code 502

### ISSUE THREAD

**Issue by kunode** [cooderl/wewe-rss#204]
用的docker-compose.sqlite.yml 部署的。

{"log":"Prisma schema loaded from prisma/schema.prisma\n","stream":"stdout","time":"2024-07-14T10:47:56.814650363Z"}
{"log":"Datasource \"db\": SQLite database \"wewe-rss.db\" at \"file:../data/wewe-rss.db\"\n","stream":"stdout","time":"2024-07-14T10:47:56.840498092Z"}
{"log":"\n","stream":"stdout","time":"2024-07-14T10:47:56.933139324Z"}
{"log":"SQLite database wewe-rss.db created at file:../data/wewe-rss.db\n","stream":"stdout","time":"2024-07-14T10:47:56.933428741Z"}
{"log":"\n","stream":"stdout","time":"2024-07-14T10:47:56.957515807Z"}
{"log":"1 migration found in prisma/migrations\n","stream":"stdout","time":"2024-07-14T10:47:56.957787706Z"}
{"log":"\n","stream":"stdout","time":"2024-07-14T10:47:56.958205969Z"}
{"log":"Applying migration `20240301104100_init`\n","stream":"stdout","time":"2024-07-14T10:47:57.050718513Z"}
{"log":"\n","stream":"stdout","time":"2024-07-14T10:47:57.397067985Z"}
{"log":"The following migration(s) have been applied:\n","stream":"stdout","time":"2024-07-14T10:47:57.398395939Z"}
{"log":"\n","stream":"stdout","time":"2024-07-14T10:47:57.398429076Z"}
{"log":"migrations/\n","stream":"stdout","time":"2024-07-14T10:47:57.398436854Z"}
{"log":"  └─ 20240301104100_init/\n","stream":"stdout","time":"2024-07-14T10:47:57.398441961Z"}
{"log":"    └─ migration.sql\n","stream":"stdout","time":"2024-07-14T10:47:57.398447652Z"}
{"log":"      \n","stream":"stdout","time":"2024-07-14T10:47:57.398452537Z"}
{"log":"All migrations have been successfully applied.\n","stream":"stdout","time":"2024-07-14T10:47:57.39845734Z"}
{"log":"npm notice \n","stream":"stderr","time":"2024-07-14T10:47:57.518571195Z"}
{"log":"npm notice New minor version of npm available! 10.5.2 -\u003e 10.8.2\n","stream":"stderr","time":"2024-07-14T10:47:57.519304831Z"}
{"log":"npm notice Changelog: \u003chttps://github.com/npm/cli/releases/tag/v10.8.2\u003e\n","stream":"stderr","time":"2024-07-14T10:47:57.519958213Z"}
{"log":"npm notice Run `npm install -g npm@10.8.2` to update!\n","stream":"stderr","time":"2024-07-14T10:47:57.521097039Z"}
{"log":"npm notice \n","stream":"stderr","time":"2024-07-14T10:47:57.521826074Z"}
{"log":"CRON_EXPRESSION:  undefined\n","stream":"stdout","time":"2024-07-14T10:47:58.947718416Z"}
{"log":"appVersion: v2.3.1\n","stream":"stdout","time":"2024-07-14T10:47:59.096424585Z"}
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[NestFactory] \u001b[39m\u001b[32mStarting Nest application...\u001b[39m\n","stream":"stdout","time":"2024-07-14T10:47:59.>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mPrismaModule dependencies initialized\u001b[39m\u001b[38;5;3m +56ms\u001b[39m\n","str>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mConfigHostModule dependencies initialized\u001b[39m\u001b[38;5;3m +2ms\u001b[39m\n",">
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mDiscoveryModule dependencies initialized\u001b[39m\u001b[38;5;3m +0ms\u001b[39m\n","s>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mConfigModule dependencies initialized\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","stre>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mConfigModule dependencies initialized\u001b[39m\u001b[38;5;3m +0ms\u001b[39m\n","stre>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mScheduleModule dependencies initialized\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","st>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mThrottlerModule dependencies initialized\u001b[39m\u001b[38;5;3m +16ms\u001b[39m\n",">
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mTrpcModule dependencies initialized\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","stream>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mAppModule dependencies initialized\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","stream">
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[InstanceLoader] \u001b[39m\u001b[32mFeedsModule dependencies initialized\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","strea>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[RoutesResolver] \u001b[39m\u001b[32mAppController {/}:\u001b[39m\u001b[38;5;3m +20ms\u001b[39m\n","stream":"stdout","time>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[RouterExplorer] \u001b[39m\u001b[32mMapped {/, GET} route\u001b[39m\u001b[38;5;3m +4ms\u001b[39m\n","stream":"stdout","ti>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[RouterExplorer] \u001b[39m\u001b[32mMapped {/robots.txt, GET} route\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","stream":"s>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[RouterExplorer] \u001b[39m\u001b[32mMapped {/favicon.ico, GET} route\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","stream":">
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[RouterExplorer] \u001b[39m\u001b[32mMapped {/dash*, GET} route\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","stream":"stdout>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[RoutesResolver] \u001b[39m\u001b[32mFeedsController {/feeds}:\u001b[39m\u001b[38;5;3m +0ms\u001b[39m\n","stream":"stdout">
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[RouterExplorer] \u001b[39m\u001b[32mMapped {/feeds, GET} route\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","stream":"stdout>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[RouterExplorer] \u001b[39m\u001b[32mMapped {/feeds/all.(json|rss|atom), GET} route\u001b[39m\u001b[38;5;3m +1ms\u001b[39m>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[RouterExplorer] \u001b[39m\u001b[32mMapped {/feeds/:feed, GET} route\u001b[39m\u001b[38;5;3m +1ms\u001b[39m\n","stream":">
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:47:59 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[NestApplication] \u001b[39m\u001b[32mNest application successfully started\u001b[39m\u001b[38;5;3m +121ms\u001b[39m\n","s>
{"log":"Server is running at http://0.0.0.0:4000\n","stream":"stdout","time":"2024-07-14T10:47:59.384384156Z"}
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:48:15 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[FeedsService] \u001b[39m\u001b[32mhandleGenerateFeed articles: 0\u001b[39m\n","stream":"stdout","time":"2024-07-14T10:48:>
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:48:23 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[FeedsService] \u001b[39m\u001b[32mhandleGenerateFeed articles: 0\u001b[39m\n","stream":"stdout","time":"2024-07-14T10:48:>
{"log":"\u001b[95m[Nest] 70  - \u001b[39m07/14/2024, 10:48:34 AM \u001b[95m  DEBUG\u001b[39m \u001b[38;5;3m[TrpcService] \u001b[39m\u001b[95mdisabledAccounts: \u001b[39m\n","stream":"stdout","time":"2024-07-14T10:48:34.401287927Z>
{"log":"\u001b[95m[Nest] 70  - \u001b[39m07/14/2024, 10:48:34 AM \u001b[95m  DEBUG\u001b[39m \u001b[38;5;3m[TrpcService] \u001b[39m\u001b[95mObject:\u001b[39m\n","stream":"stdout","time":"2024-07-14T10:48:34.401778606Z"}
{"log":"[]\n","stream":"stdout","time":"2024-07-14T10:48:34.401798744Z"}
{"log":"\n","stream":"stdout","time":"2024-07-14T10:48:34.401809129Z"}
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:48:36 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[TrpcService] \u001b[39m\u001b[32merror: \u001b[39m\n","stream":"stdout","time":"2024-07-14T10:48:36.338770125Z"}
{"log":"\u001b[32m[Nest] 70  - \u001b[39m07/14/2024, 10:48:36 AM \u001b[32m    LOG\u001b[39m \u001b[38;5;3m[TrpcService] \u001b[39m\u001b[32mAxiosError: Request failed with status code 500\u001b[39m\n","stream":"stdout","time":"2>
{"log":"\u001b[31m[Nest] 70  - \u001b[39m07/14/2024, 10:48:36 AM \u001b[31m  ERROR\u001b[39m \u001b[38;5;3m[TrpcService] \u001b[39m\u001b[31mCan't handle this error: \u001b[39m\n","stream":"stderr","time":"2024-07-14T10:48:36.340>
{"log":"connect ECONNREFUSED 146.235.218.96:3008\n","stream":"stderr","time":"2024-07-14T10:48:36.340965522Z"}

**Comment by xiangyile** [comment]
我用的MySQL，也遇到这种情况

**Comment by le0zh0u** [comment]
这个日志看起来好累，这个和数据库没有关系，连接中转服务问题。我看现在是好的，你可以手动同步一下，看是否会报错。
