### ISSUE TITLE
Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.

### ISSUE THREAD

**Issue by Liumeng404** [cooderl/wewe-rss#205]
部署成功了，但一直显示这个：
![QQ截图20240720182522](https://github.com/user-attachments/assets/0b823656-e8f0-4044-b4ae-c5b061df15bf)

**Comment by Swim0o0** [comment]
same.
![Snipaste_2024-07-22_08-06-27](https://github.com/user-attachments/assets/83f5cdd9-7c0d-4bd3-96df-72d062483a58)

**Comment by Liumeng404** [comment]
已解决，是在输入auth时，是喔输入的字符有问题。
