### ISSUE TITLE
现在是限制了每天新加公众号的数量了吗？

### ISSUE THREAD

**Issue by KINAXNG** [cooderl/wewe-rss#208]
新搭的服务，1个读书号，添加3个后再添加，确定按钮灰了，是每天限制还是单个读书号限制？

另外，总共可以添加多少个公众号？有没有上限？

**Comment by ztm0929** [comment]
之前有网友提到显示的上限是500个，但实际到达500个后可以继续添加👀

#114

**Comment by KINAXNG** [comment]
![局部截取_20240723_235730](https://github.com/user-attachments/assets/0c4bd6ec-99fb-4771-9e22-17202c3b1c77)
难道这是bug? feed地址可访问
