### ISSUE TITLE
如何进入、查看小黑屋？

### ISSUE THREAD

**Issue by katfionn** [cooderl/wewe-rss#211]
# 环境

基于casaos面板安装

# 需求

1、在进入容器的终端界面后，如何进入小黑屋？
2、进入后，如何查看小黑屋？

大佬们帮忙解惑下，谢谢

**Comment by le0zh0u** [comment]
小黑屋是保存在运行上下文中。没有接口查看。你可以直接在账号管理中看哪些账号被加入小黑屋了。会在第二天或者服务重启后刷新。

**Comment by katfionn** [comment]
好，谢谢了

> 小黑屋是保存在运行上下文中。没有接口查看。你可以直接在账号管理中看哪些账号被加入小黑屋了。会在第二天或者服务重启后刷新。
