### ISSUE TITLE
域名是不是挂了

### ISSUE THREAD

**Issue by wyn-ying** [cooderl/wewe-rss#214]
docker部署wewe-rss-sqlite无法刷新，也无法添加读书账号，查看logs发现一直在[TrpcService] AxiosError: timeout of 15000ms exceeded
尝试curl https://weread.111965.xyz/也不通，不过意外发现curl走科学上网可以通
不知道有没有类似情况？

**Comment by insogao** [comment]
同样是docker部署，也是一样的情况。请求失败!

**Comment by wyn-ying** [comment]
@cooderl 大佬，我找了4台设备分别部署了docker版本，腾讯云服务器上可以work，阿里云和家用环境的两台都会挂。
我trace了一下网络传输路径，腾讯云服务器traceroute能找到域名对应的ip（走的电信网络）；
阿里云服务器（走的阿里云自己的运营商）和家用环境（联通）traceroute都跳一半就断掉了。
应该是你这个域名被干了...

**Comment by insogao** [comment]
> @cooderl 大佬，我找了4台设备分别部署了docker版本，腾讯云服务器上可以work，家用环境的两台设备和阿里云服务器上面都会挂。 我trace了一下网络传输路径，腾讯云服务器traceroute能找到域名对应的ip（走的电信网络）； 阿里云服务器（走的阿里云自己的运营商）和家用环境（联通）traceroute都跳一半就断掉了。 应该是你这个域名被干了...

大佬，docker不是本地部署吗。还是说本地部署也要依赖一个外部的服务..

**Comment by wyn-ying** [comment]
> > @cooderl 大佬，我找了4台设备分别部署了docker版本，腾讯云服务器上可以work，家用环境的两台设备和阿里云服务器上面都会挂。 我trace了一下网络传输路径，腾讯云服务器traceroute能找到域名对应的ip（走的电信网络）； 阿里云服务器（走的阿里云自己的运营商）和家用环境（联通）traceroute都跳一半就断掉了。 应该是你这个域名被干了...
> 
> 大佬，docker不是本地部署吗。还是说本地部署也要依赖一个外部的服务..

你再仔细看看readme....或者直接在repo里搜一下这个域名，看看代码就懂了，依赖了这个域名的
