### ISSUE TITLE
又无法更新了？

### ISSUE THREAD

**Issue by elain** [cooderl/wewe-rss#215]
![image](https://github.com/user-attachments/assets/830a9b94-f9cd-4437-9828-a740952ae365)

**Comment by elain** [comment]
我排查了下看，在我的云主机上是无法访问  weread.111965.xyz  这个域名的，我本地是可以访问的。 

请问作者，是否在weread.111965.xyz 这个域名侧有做一些 IP 的限制访问，尤其是对公有云，我使用的是华为云的主机，IP 段是 120.46.x.x 开头。
![image](https://github.com/user-attachments/assets/6da3728e-8338-4b5a-ab96-70b5e7d25f8a)

**Comment by wyn-ying** [comment]
#214 应该是一个问题

**Comment by cooderl** [comment]
> 我排查了下看，在我的云主机上是无法访问 weread.111965.xyz 这个域名的，我本地是可以访问的。
> 
> 请问作者，是否在weread.111965.xyz 这个域名侧有做一些 IP 的限制访问，尤其是对公有云，我使用的是华为云的主机，IP 段是 120.46.x.x 开头。 ![image](https://private-user-images.githubusercontent.com/3030333/353298371-6da3728e-8338-4b5a-ab96-70b5e7d25f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTk3NDIsIm5iZiI6MTcyMjMxOTQ0MiwicGF0aCI6Ii8zMDMwMzMzLzM1MzI5ODM3MS02ZGEzNzI4ZS04MzM4LTRiNWEtYWI5Ni03MGI1ZTdkMjVmOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMDYwNDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzk5NmMxMmE3ODY3Nzc0YzZiMjNkN2ZlOGVmZmQ5YWUxYjIwNTFiMTVlNTA3NzAyNmYwZTVlMjQ0NDVmNjM0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Jx3shX3aE-b_23rfidFBiCkU_BnHmh94Xu4ccyXR_0A)

域名托管在cloudflare，走了它的加速，部分地区可能是被污染了
