### ISSUE TITLE
建议修改 web、feed 中的 wewe-rss.png 资源地址

### ISSUE THREAD

**Issue by buggithubs** [cooderl/wewe-rss#220]
在 web 页面、对外的 feed 数据流均有如下链接的硬编码，该资源在 CN 区域需要科学上网访问，无法直接访问；  
会影响到 CN 区域 freshrss 使用 wewe-rss 的 feed 订阅

`https://r2-assets.111965.xyz/wewe-rss.png`

是否可以修改为 wewe-rss 私有化部署资源的地址？
修改后同步可降低 111965.xyz 主机成本和压力

**Comment by wyn-ying** [comment]
可以参考这个[PR](https://github.com/cooderl/wewe-rss/pull/224)
如果用户配置了 `SERVER_ORIGIN_URL` 参数，则png资源由`SERVER_ORIGIN_URL/favicon.ico` 接口提供
如果用户不配置 `SERVER_ORIGIN_URL`，再走 `https://r2-assets.111965.xyz/wewe-rss.png`
