### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Mait31** [cooderl/wewe-rss#24]
![image](https://github.com/cooderl/wewe-rss/assets/85567149/68880ba8-d3ba-4e44-b01f-22a6f92b1032)
您好，我部署完之后打开提示Failed to fetch，这是为什么呢？

**Comment by Mait31** [comment]
![image](https://github.com/cooderl/wewe-rss/assets/85567149/1bb201d2-dd12-40cd-9b59-704a308504d5)
我使用了nginx反向代理，提示如上

**Comment by cooderl** [comment]
需要修改 SERVER_ORIGIN_URL 为域名地址

**Comment by Mait31** [comment]
SERVER_ORIGIN_URL可以设置为https么，我修改为域名地址也出现了相同的状况

**Comment by cooderl** [comment]
可以https的

**Comment by Mait31** [comment]
可以生成RSS订阅供其他软件使用么

**Comment by cooderl** [comment]
可以试一下1.7.0镜像，SERVER_ORIGIN_URL 是可选了。
