### ISSUE TITLE
想了解一下每天的更新时间是可以设定的吗？目前的更新都集中在凌晨5点

### ISSUE THREAD

**Issue by mqq982068** [cooderl/wewe-rss#243]
![image](https://github.com/user-attachments/assets/526fc9fc-c258-495e-828d-486234d1b1b7)

**Comment by wyn-ying** [comment]
看一下参数 CRON_EXPRESSION

**Comment by mqq982068** [comment]
我添加了这个环境变量，也重建了项目，但日志里还是只有5点的更新。添加完这个参数还需要设置什么吗

**Comment by Cyiming** [comment]
> 我添加了这个环境变量，也重建了项目，但日志里还是只有5点的更新。添加完这个参数还需要设置什么吗

你解决了么

**Comment by mqq982068** [comment]
解决了，不光这个参数，还有一个时区的环境变量，也得加进去。
你看看你显示最开始更新的时间和你设置的时间是不是固定的隔几个小时，如果是的话就是时区变量的关系。
TZ: 'Asia/Shanghai'

**Comment by Cyiming** [comment]
> 解决了，不光这个参数，还有一个时区的环境变量，也得加进去。 你看看你显示最开始更新的时间和你设置的时间是不是固定的隔几个小时，如果是的话就是时区变量的关系。 TZ: 'Asia/Shanghai'

是的 你说的对 我还提交了bug刚刚

但是我的时区是      TZ: 'Asia/Shanghai' 啊 但是系统显示的时间现在是2024-12-20T06:00:57.000Z

**Comment by mqq982068** [comment]
改完要重新部署的，光重启不行

**Comment by Cyiming** [comment]
> 改完要重新部署的，光重启不行

嗯嗯 重新部署了 就是我的docker-compose默认就是TZ: 'Asia/Shanghai'  我没修改 
![PixPin_2024-12-20_14-13-19](https://github.com/user-attachments/assets/47342033-4b02-4dd4-9266-a544fc143732)
我的定时是CRON_EXPRESSION=0 */15 5-23 * *

**Comment by mqq982068** [comment]
- CRON_EXPRESSION=30 8,11 * * *            我的是这样的，没看懂你段 是啥设置

**Comment by Cyiming** [comment]
> * CRON_EXPRESSION=30 8,11 * * *            我的是这样的，没看懂你段 是啥设置

偷懒了 用豆包弄的 搞错了 应该是CRON_EXPRESSION=*/15 5-23 * * *  改完之后更了 但是follow不同步 我再观察下
