### ISSUE TITLE
RSS客户端订阅后，只能看见文章的标题，没有文章内容

### ISSUE THREAD

**Issue by AlanHootman** [cooderl/wewe-rss#245]
RSS客户端订阅后，只能看见文章的标题，没有文章内容

**Comment by cooderl** [comment]
看一下服务端日志，是否成功拉取到了文章的内容

**Comment by joyous-coder** [comment]
![image](https://github.com/user-attachments/assets/8f5bba31-1f76-4302-9d9c-a7f76c051543)
我的rss也只有标题没有内容

**Comment by joyous-coder** [comment]
我的也是，并没有报错。
![image](https://github.com/user-attachments/assets/60147e50-87f0-4ab2-9bce-dbc10fdfbfbe)

**Comment by joyous-coder** [comment]
这个里面只有标题和链接，这个是正常的吗？？
![image](https://github.com/user-attachments/assets/b2124ada-4671-46c5-8cda-f5759053cabd)

**Comment by joyous-coder** [comment]
docker里面      - FEED_MODE=fulltext 环境变量设置上就正常了

**Comment by AlanHootman** [comment]
docker里面 - FEED_MODE=fulltext 环境变量设置上就正常了
