### ISSUE TITLE
服务又报 500 异常了

### ISSUE THREAD

**Issue by ginobefun** [cooderl/wewe-rss#257]
[Nest] 70  - 09/29/2024, 1:22:51 AM     LOG [FeedsService] handleGenerateFeed articles: 10
[Nest] 70  - 09/29/2024, 1:22:51 AM     LOG [FeedsController] getFeed:
[Nest] 70  - 09/29/2024, 1:22:51 AM     LOG [FeedsController] MP_WXS_3220072307
[Nest] 70  - 09/29/2024, 1:22:51 AM     LOG [FeedsService] handleGenerateFeed articles: 10
[Nest] 70  - 09/29/2024, 1:22:52 AM     LOG [TrpcService] error:
[Nest] 70  - 09/29/2024, 1:22:52 AM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 70  - 09/29/2024, 1:22:52 AM   ERROR [TrpcService] Can't handle this error:
refreshLoginToken(8839617) failed
[Nest] 70  - 09/29/2024, 1:22:52 AM   ERROR [TrpcService] retry(1) getMpArticles  error:
[Nest] 70  - 09/29/2024, 1:22:52 AM   ERROR [TrpcService] AxiosError: Request failed with status code 500
[Nest] 70  - 09/29/2024, 1:22:52 AM   DEBUG [TrpcService] disabledAccounts:
[Nest] 70  - 09/29/2024, 1:22:52 AM   DEBUG [TrpcService] Object:
[]

**Comment by edison12-star** [comment]
我也是，好不容易能用两天，比较不稳定

**Comment by Ymriri** [comment]
我的是请求超时....也是部署2天...

**Comment by cooderl** [comment]
好了
