### ISSUE TITLE
关于  SERVER_ORIGIN_URL 的设置要求

### ISSUE THREAD

**Issue by yefoenix** [cooderl/wewe-rss#26]
请问 SERVER_ORIGIN_URL 是必须固定设置的吗？能否留空允许不同的地址？
因为在不同场景下，可能需要在不同的地址下访问项目前端，例如——
本机下 127.0.0.1:4000，
局域网内其他机器上 192.168.*.*:4000，
Tailscale 远程组网又会有一个网段，如果设置了外网域名反代，还会有域名访问需求

**Comment by cooderl** [comment]
这个变量是用于rss生成时候组合rss地址。其实也可以按照你说的这样，我看看哪些地方需要改一下

**Comment by cooderl** [comment]
可以试一下1.7.0镜像
