### ISSUE TITLE
Reeder 5 ，不显示文章内容

### ISSUE THREAD

**Issue by Li-Jack** [cooderl/wewe-rss#27]
Docker搭建，使用yaml文件启动，新建公众号的RSS订阅，没有显示内容，麻烦看一下的
@cooderl 
<img width="1268" alt="image" src="https://github.com/cooderl/wewe-rss/assets/49050607/61dcbf23-39a5-4525-a9ce-1e2e8644aec5">

**Comment by Li-Jack** [comment]
估计是我操作的问题，但是不知道啥情况

**Comment by cooderl** [comment]
有个环境变量feed_mode没有配置，可以看一下readme

**Comment by Li-Jack** [comment]
可以了，谢谢

**Comment by zhyine** [comment]
同样Reeder 5。公众号“宫水三叶刷题日记”不显示内容，但是它的RSS链接里面可以看到内容信息。
<img width="754" alt="image" src="https://github.com/cooderl/wewe-rss/assets/45561781/0ede3ec3-95c9-4e4d-b4d8-0f522d3b1464">
<img width="1897" alt="image" src="https://github.com/cooderl/wewe-rss/assets/45561781/e1e46704-71ae-4cfc-8c7f-582715b786a2">
<img width="753" alt="image" src="https://github.com/cooderl/wewe-rss/assets/45561781/1e84b196-b60e-4d51-9a96-e0b31ebf3ee0">
