### ISSUE TITLE
账号状态今日小黑屋是被封了吗？

### ISSUE THREAD

**Issue by eyebrowkang** [cooderl/wewe-rss#29]
昨晚只添加了三个公众号，早上起来看到这个

<img width="431" alt="image" src="https://github.com/cooderl/wewe-rss/assets/48169104/108da8e4-c42b-436f-b969-99cd70fbb9ec">

**Comment by cooderl** [comment]
被微信读书风控了，等一天会恢复。

**Comment by lxyer** [comment]
> 被微信读书风控了，等一天会恢复。

如果一天加三个公众号就被限制，还是要想想有什么办法可以绕过

**Comment by cooderl** [comment]
> > 被微信读书风控了，等一天会恢复。
> 
> 如果一天加三个公众号就被限制，还是要想想有什么办法可以绕过

可能是操作太频繁了，一般加个十几个没问题的。
另外可以加几个读书账号

**Comment by eightHundreds** [comment]
我也是加3个就封，2天了没恢复

**Comment by eyebrowkang** [comment]
> 被微信读书风控了，等一天会恢复。

我的等了一天确实恢复了，但是我还没操作就又小黑屋了。我看三个公众号有两个刷新了订阅，第三个估计请求的时候就不行了。

我在微信看公众号是正常的，微信读书试了一下搜公众号就要一直验证。
另外，这个账号也不是新号，好多年了，只是之前从来没有登录过微信读书，我刚下载试的

**Comment by chejg** [comment]
我的也是刚出小黑屋，自动更新了两个公众号就又被风控了。
是否能够调整一下自动更新的的策略，比如定时更新后，开始每隔几分钟抓取一个公众号，这样是不是好些？

**Comment by xiaozhubin** [comment]
我的也封控了。昨天还是好的，今天就不行了。有没有什么方法规避一下？三天两头小黑屋的话，似乎就不太值得了。

**Comment by linfenglife** [comment]
隔了一天没去动也小黑屋了...

**Comment by bosconb** [comment]
我也是每天加两个号就被小黑屋了。

**Comment by yanquan2020** [comment]
微信真是玩不起

**Comment by ChchNiu** [comment]
小黑屋已经4天了，还有救吗

**Comment by DophinL** [comment]
请问下进了小黑屋，会有什么风险吗？微信本身还可用吗？
