### ISSUE TITLE
nginx反向代理+https配置，供大家参考，试了很长时间才找到的办法

### ISSUE THREAD

**Issue by Mait31** [cooderl/wewe-rss#30]
docker run -d \
  --name wewe-rss \
  -p 31620:4000 \
  -e DATABASE_URL=file:../data/wewe-rss.db \
  -e DATABASE_TYPE=sqlite \
  -e AUTH_CODE=1234567 \
  -e FEED_MODE=fulltext \
  -e MAX_REQUEST_PER_MINUTE=60 \
  -e SERVER_ORIGIN_URL=https://xxx.com:37462 \
  -v $(pwd)/data:/app/data \
  cooderl/wewe-rss-sqlite:latest

注：-e SERVER_ORIGIN_URL=https://xxx.com:port为nginx监听地址+端口

**Comment by cooderl** [comment]
SERVER_ORIGIN_URL 现在是可选值了，可以看下 readme
