### ISSUE TITLE
请求失败 二维码加载中（已解决）

### ISSUE THREAD

**Issue by Cyiming** [cooderl/wewe-rss#308]
直接ping不通 
host绑定172.64.80.1 weread.111965.xyz后能ping通 但是还是加载不出来

**Comment by 7u0** [comment]
环境变量参数 `PLATFORM_URL` 默认为 `https://weread.111965.xyz`, 如果在国内DNS解析导致请求失败可以使用 `https://weread-v.111965.xyz`

**Comment by 7u0** [comment]
可以试试改下环境变量参数 `PLATFORM_URL` ，默认为 `https://weread.111965.xyz`, 如果在国内DNS解析导致请求失败可以使用 `https://weread-v.111965.xyz`

**Comment by Cyiming** [comment]
> 可以试试改下环境变量参数 `PLATFORM_URL` ，默认为 `https://weread.111965.xyz`, 如果在国内DNS解析导致请求失败可以使用 `https://weread-v.111965.xyz`

还是不行 也ping不通
![PixPin_2024-12-06_07-55-42](https://github.com/user-attachments/assets/88132843-ccd2-49a4-aef0-abeed9668b43)

**Comment by cooderl** [comment]
试一下这个新域名能不能ping通  https://weread.965111.xyz

**Comment by Cyiming** [comment]
> 试一下这个新域名能不能ping通 https://weread.965111.xyz

这个确实能ping通

但是我PLATFORM_URL=https://weread.965111.xyz后重启了docker项目  还是加载不出 不知道问题出在哪了
