### ISSUE TITLE
部署在Hugging Face平台无法使用，求推荐新的部署方案

### ISSUE THREAD

**Issue by iar** [cooderl/wewe-rss#309]
Hugging Face平台一直显示building或者preparing sapce，排查不出原因，求推荐免费的部署方案

**Comment by Ryclock** [comment]
同样的问题，在尝试检查后怀疑是HF侧对Dockerfile进行关键词（wewe-rss）屏蔽，结果是对应的HF space被标记为异常。暂时可使用的两种解决方案如下，希望有用（**需要先删除原来的HF space，再新建**）

1. fork当前仓库（仓库名不要使用默认的wewe-rss），然后替换掉Dockerfile中的git url
![image](https://github.com/user-attachments/assets/25f44ede-6e24-4fbe-9fb2-1276754aea30)

2. 使用ARG指令将git url外置，具体见下
![image](https://github.com/user-attachments/assets/54b2c6ff-788d-43c0-97f3-bf8e0e570911)
![image](https://github.com/user-attachments/assets/e38896b0-5c4a-492a-b8cd-08f8ab2a5aec)

**Comment by powermanlong1998** [comment]
使用下面2步部署成功
1. fork当前仓库（仓库名不要使用默认的wewe-rss），然后替换掉Dockerfile中的git url
2.
dockerfile添加
RUN apk add --no-cache openssl

**Comment by tungzip** [comment]
> 使用下面2步部署成功
> 
> 1. fork当前仓库（仓库名不要使用默认的wewe-rss），然后替换掉Dockerfile中的git url
> 
> dockerfile添加 RUN apk add --no-cache openssl

我dockerfile里加了RUN apk add --no-cache openssl，还是报错，是不是还需要指定版本openssl？
![微信截图_20241215105446](https://github.com/user-attachments/assets/2b45742a-adb8-463d-ba5d-0d6f759499a5)

**Comment by iar** [comment]
感谢大神，用这个方法成功安装，需要注意RUN apk add --no-cache openssl的添加位置
# 全局安装pnpm
RUN npm i -g pnpm
RUN apk add --no-cache openssl
