### ISSUE TITLE
建议增加纯阅读模式，便于小范围分享。

### ISSUE THREAD

**Issue by lmm214** [cooderl/wewe-rss#31]
好项目！感谢作者～

现有是进入即管理模式，若多人使用，会存在数据混乱，误操作等问题。

若可以改为阅读模式（可选：阅读登录码），点击设置管理员登录后才能管理。

另外，移动端样式需要优化。

**Comment by yefoenix** [comment]
这个是生成 rss feed 用的，阅读的话直接用 rss 阅读器就行了
