### ISSUE TITLE
请问为什么我点添加账号，显示请求失败？

### ISSUE THREAD

**Issue by LUlu0113** [cooderl/wewe-rss#312]
![屏幕截图 2024-12-05 135654](https://github.com/user-attachments/assets/3c7267ce-d028-4041-95c9-c35c6a65a053)
![屏幕截图 2024-12-05 135703](https://github.com/user-attachments/assets/c96345ea-ddcb-40bd-ba06-2e4b567e1408)
可以麻烦各位老师帮我看一下吗？不是很懂，调试了很久也不行。非常感谢各位！！

**Comment by 1nhann** [comment]
@LUlu0113 楼主找到原因了吗
