### ISSUE TITLE
容器版wewerss如何进行健康检查healthcheck？

### ISSUE THREAD

**Issue by 0ptimista** [cooderl/wewe-rss#315]
是否有公开API端点可以进行健康检查？

**Comment by le0zh0u** [comment]
这是需要检查服务是否可用还是什么。

**Comment by 0ptimista** [comment]
> 这是需要检查服务是否可用还是什么。

是的。有接口返回服务是否正常。

**Comment by le0zh0u** [comment]
可以直接访问首页，http://127.0.0.1:3000，如果能返回200，意味着服务是正常的，如果再严谨一些，就是判断获取的html中是否有wewe rss的内容，具体可以看下AppService中的返回内容
后端提供了两个开放的api， 一个是/，一个/robots.txt

**Comment by 0ptimista** [comment]
> 可以直接访问首页，[http://127.0.0.1:3000，如果能返回200，意味着服务是正常的，如果再严谨一些，就是判断获取的html中是否有wewe](http://127.0.0.1:3000%EF%BC%8C%E5%A6%82%E6%9E%9C%E8%83%BD%E8%BF%94%E5%9B%9E200%EF%BC%8C%E6%84%8F%E5%91%B3%E7%9D%80%E6%9C%8D%E5%8A%A1%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%EF%BC%8C%E5%A6%82%E6%9E%9C%E5%86%8D%E4%B8%A5%E8%B0%A8%E4%B8%80%E4%BA%9B%EF%BC%8C%E5%B0%B1%E6%98%AF%E5%88%A4%E6%96%AD%E8%8E%B7%E5%8F%96%E7%9A%84html%E4%B8%AD%E6%98%AF%E5%90%A6%E6%9C%89wewe) rss的内容，具体可以看下AppService中的返回内容 后端提供了两个开放的api， 一个是/，一个/robots.txt

看起来 `curl http://127.0.0.1:4000` 是可以作为健康检查的。 不过我看到目前Dockerfile中在构建时并没有添加`curl` 软件包。 需要提PR修改吗？

**Comment by YU-7** [comment]
![image](https://github.com/user-attachments/assets/7dccb13e-30fa-4308-8034-26ae8f0c2903)
```
 healthcheck:
      test: ["CMD", "wget", "--spider", "http://127.0.0.1:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
可以用这个

> > 可以直接访问首页，[http://127.0.0.1:3000，如果能返回200，意味着服务是正常的，如果再严谨一些，就是判断获取的html中是否有wewe](http://127.0.0.1:3000%EF%BC%8C%E5%A6%82%E6%9E%9C%E8%83%BD%E8%BF%94%E5%9B%9E200%EF%BC%8C%E6%84%8F%E5%91%B3%E7%9D%80%E6%9C%8D%E5%8A%A1%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%EF%BC%8C%E5%A6%82%E6%9E%9C%E5%86%8D%E4%B8%A5%E8%B0%A8%E4%B8%80%E4%BA%9B%EF%BC%8C%E5%B0%B1%E6%98%AF%E5%88%A4%E6%96%AD%E8%8E%B7%E5%8F%96%E7%9A%84html%E4%B8%AD%E6%98%AF%E5%90%A6%E6%9C%89wewe) rss的内容，具体可以看下AppService中的返回内容 后端提供了两个开放的api， 一个是/，一个/robots.txt
> 
> 看起来 `curl http://127.0.0.1:4000` 是可以作为健康检查的。 不过我看到目前Dockerfile中在构建时并没有添加`curl` 软件包。 需要提PR修改吗？

**Comment by YU-7** [comment]
这个是busybox（docker自带的一个工具包）基本上每一个容器都会有的命令

**Comment by 0ptimista** [comment]
感谢！
