### ISSUE TITLE
v2.6.0 版本 run不起来 Prisma Client 初始化错误 Ubuntu 22.04

### ISSUE THREAD

**Issue by tank-long** [cooderl/wewe-rss#321]
# Bug 反馈：v2.6.0 版本 Prisma Client 初始化错误

## 问题描述
wewe-rss-sqlite 最新版本（v2.6.0）因 Prisma Client 初始化错误而无法启动，具体与 OpenSSL 兼容性有关。

## 环境信息
- Docker 镜像：cooderl/wewe-rss-sqlite:latest
- 主机系统：Ubuntu 22.04 LTS（如果版本不对，请修改为你的实际版本）
- Node.js 版本：v20.18.1
- Prisma 版本：5.10.1

## 错误信息
PrismaClientInitializationError: Unable to require(/app/node_modules/.pnpm/@prisma+client@5.10.1_prisma@5.10.2/node_modules/.prisma/client/libquery_engine-linux-musl.so.node).
The Prisma engines do not seem to be compatible with your system.
详细错误：Error loading shared library libssl.so.1.1: No such file or directory

## 复现步骤
1. 拉取最新镜像：docker pull cooderl/wewe-rss-sqlite:latest
2. 使用 docker-compose 运行

## 补充信息
- 错误似乎与 Alpine 基础镜像中的 OpenSSL 兼容性有关
- 之前的版本可以正常运行
- 尝试过安装 openssl1.1-compat 或 openssl3，但问题仍未解决

## 临时解决方案
目前通过使用旧版本镜像来解决

**Comment by Aduhelmer** [comment]
+1

**Comment by cooderl** [comment]
升级 v2.6.1 ok了
