### ISSUE TITLE
网页界面缺失拉取历史文章

### ISSUE THREAD

**Issue by dadaomamao** [cooderl/wewe-rss#325]
![image](https://github.com/user-attachments/assets/d90b027c-d682-4d2b-8a27-01aa05395ab7)
更新2.6.1后缺失功能或功能界面拉取历史文章，已经清除过浏览器Cooke及缓存 重启过服务器 服务器 乌班图22

**Comment by dadaomamao** [comment]
已在单独公众号界面找到该选项

**Comment by yuluoqingcheng** [comment]
请问在哪里找到的

**Comment by yuluoqingcheng** [comment]
单独公众号页面也没有啊 

![Image](https://github.com/user-attachments/assets/990809a5-1c80-4a2c-aa05-1c87dd851811)
