### ISSUE TITLE
【建议】能否增加网页链接添加？

### ISSUE THREAD

**Issue by Cyiming** [cooderl/wewe-rss#326]
网页链接这种无法添加 不知道有没有算法自动识别变成短链
https://mp.weixin.qq.com/s?__biz=MzI1MTQ2NzQ0NQ==&mid=2247500003&idx=1&sn=5fbc2e9927cdb83e75824e71d192a51b&chksm=e827e3b6be02d1fa6efd157253d8281a404846841d110ea92fc75053c2b78713a102a31aa2db&scene=126&sessionid=1732239680#rd

我是用pc端微信筛选公众号关注的 现在得浏览器打开 然后再用手机微信去复制链接

**Comment by cooderl** [comment]
这个链接不是文章的真实链接，用不了额

**Comment by Cyiming** [comment]
> 这个链接不是文章的真实链接，用不了额

长链才是真实链接 短链是转换的
