### ISSUE TITLE
Bug：更新2.5.0和2.6.1后订阅源出现问题

### ISSUE THREAD

**Issue by jpjpszz** [cooderl/wewe-rss#327]
我从2.4.2升级到2.5.0和2.6.1后订阅源好像发生了问题，在FreshRSS和Follow里都订阅失败（旧订阅源弹警报无法再更新，新订阅源无法添加）。
但而在wewerss是正常运作的也可以看到更新的，就是无法在RSS阅读器里更新与添加。使用的订阅源是默认的.atom格式。
之前我是从2.5.0退回了2.4.2，就正常了。
现在2.6.1更新后也出现这个问题，感觉不能一直待在2.4.2，所以还是提了这个issue。
如果我提供更多的日志或资料什么的，请留言

图1
![image](https://github.com/user-attachments/assets/b3be5bac-2a52-4b57-9eb5-9506a1270e50)
图2
![image](https://github.com/user-attachments/assets/0e98ef0f-ba64-40a6-96df-6712d8ce19c0)
图3
![image](https://github.com/user-attachments/assets/9e628cc2-e11a-4753-84be-d08c5528631d)

**Comment by jpjpszz** [comment]
> 试一下添加环境变量 ENABLE_CLEAN_HTML=true

好了，已恢复正常，谢谢这么快的回复^^

**Comment by niehaochen666-del** [comment]
请问怎么搞好的，纯小白好不容易部署好，folo里面没数据
