### ISSUE TITLE
微信毛病真多，阅读快了 也不行，大家注意

### ISSUE THREAD

**Issue by Cyiming** [cooderl/wewe-rss#330]
看到十多个就这样了
![PixPin_2024-12-17_20-51-07](https://github.com/user-attachments/assets/03ec2cde-965c-4eba-80b3-2ba20abd0a39)
大家yu'dc遇到过么 多久恢复？

**Comment by DeSireFire** [comment]
也不是毛病，微信故意的。
这是风控限制，反爬的。
