### ISSUE TITLE
2.6.1版本在follow里不显示图片和详情

### ISSUE THREAD

**Issue by xqzlw** [cooderl/wewe-rss#334]
![PixPin_2024-12-19_10-26-47](https://github.com/user-attachments/assets/a009afa6-33b3-477e-8b14-723ae876741f)
在follow里不显示图片和详情，原本是会显示的

**Comment by cooderl** [comment]
添加环境变量 ENABLE_CLEAN_HTML=true ，开启文章内容清理，这个配置在2.6.1是默认关闭了
