### ISSUE TITLE
前几天不是有web和server端docker部署吗？为什么现在只有server端docker部署了？

### ISSUE THREAD

**Issue by buertang** [cooderl/wewe-rss#40]
根据前几天的docker命令成功运行，但是使用现在的docker命令，web端无法使用。
现在：
docker run -d \
  --name wewe-rss \
  -p 4000:4000 \
  -e DATABASE_URL='mysql://root:123456@db:3306/wewe-rss?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30' \
  -e AUTH_CODE=123567 \
  --network wewe-rss \
  cooderl/wewe-rss:latest
以后只有cooderl/wewe-rss这一个docker了吗？前后端不分离吗？

**Comment by cooderl** [comment]
之前前端用的nextjs，所以分成了两个镜像。
后来发现 nextjs 容器问题太多，索性用vite+react重构，前后端就打成一个镜像了。
