### ISSUE TITLE
我就加了一个公众号就进小黑屋了，两天都是。更新都不敢点一下的。

### ISSUE THREAD

**Issue by yfowsoulhq** [cooderl/wewe-rss#55]

**Comment by cooderl** [comment]
之前有用过微信读书嘛，登录微信读书app看看有没有什么提示

**Comment by yfowsoulhq** [comment]
> 之前有用过微信读书嘛，登录微信读书app看看有没有什么提示

之前没有用过，刚刚下载了进去看看，什么提示也没有。这个和公众号什么关联吗，不太清楚

**Comment by nevertoday** [comment]
这个小黑屋要呆多少天哦~ 我也是一个帐号就黑了

**Comment by xinmans** [comment]
今天突然进小黑屋了

**Comment by nevertoday** [comment]
每天都是小黑屋！！！

**Comment by xinmans** [comment]
没救了

**Comment by Hello-RXM** [comment]
同样的问题，就添加了一个公众号，第二天就进小黑屋了

**Comment by cooderl** [comment]
更新2.x版本，使用更加稳定的微信接口 #96

**Comment by nevertoday** [comment]
确实好了， 弱弱的请问： 后续是不是有分组功能
再弱弱弱的请问： 能不能获取到每篇微信文章的阅读量？
