### ISSUE TITLE
抓取跟多历史文章

### ISSUE THREAD

**Issue by Li-Jack** [cooderl/wewe-rss#65]
能否支持抓取历史文章的的数量自定义，现在新添加的文章只支持支持抓取10篇

**Comment by nashsu** [comment]
是说rss的吗？rss可以在连接后面加上limit参数，如:
/feeds/MP_WXS_3241469220.atom?limit=20
这样就可以将数量增加为20。
说明里没写，我也是看了源代码才知道可以有这个参数

**Comment by Li-Jack** [comment]
Thanks♪(･ω･)ﾉ

**Comment by utccnu** [comment]
> 是说rss的吗？rss可以在连接后面加上limit参数，如:
> 
> `/feeds/MP_WXS_3241469220.atom?limit=20 `
> 
> 这样就可以将数量增加为20。 说明里没写，我也是看了源代码才知道可以有这个参数

hi,刚刚试了我添加的一个公众号，limit=100 也跟 wewe-rss 网页端看到的数量一样，都只能到上个月某天的。。是不是还需要更多的操作配置？

**Comment by EricZhou05** [comment]
谢谢找半天issue终于找到解法了
