### ISSUE TITLE
无法添加读书账号

### ISSUE THREAD

**Issue by toyqiu** [cooderl/wewe-rss#66]
![image](https://github.com/cooderl/wewe-rss/assets/479873/04749e6b-d76b-48f6-a115-5f93e4fcc3c8)
![image](https://github.com/cooderl/wewe-rss/assets/479873/75d61313-6e2f-495e-ac0a-7d6b4744332d)

**Comment by cooderl** [comment]
ping一下这个域名试试` ping weread.111965.xyz`

**Comment by cooderl** [comment]
更新2.x版本，使用更加稳定的微信接口 #96
