### ISSUE TITLE
能支持sqlite吗?

### ISSUE THREAD

**Issue by eightHundreds** [cooderl/wewe-rss#7]
不想启动2个服务

**Comment by cooderl** [comment]
加上sqlite的镜像了

参考 

https://github.com/cooderl/wewe-rss/blob/main/docker-compose.sqlite.yml

**Comment by eightHundreds** [comment]
既然用了sqlite,就没必要docker-compose.  一个Dockerfile或者一个js脚本 解决(这样能支持很多云平台发布)
