### ISSUE TITLE
使用Readwise Reader无法添加订阅源

### ISSUE THREAD

**Issue by ChchNiu** [cooderl/wewe-rss#79]
非常感谢您的开源项目
我使用Docker部署了Sqlite版本的项目，部署成功后绑定我的域名。
但是无法在Readwise Reader中订阅RSS。
我生成的RSS订阅如下所示：https://xxx.com/feeds/MP_WXS_3873892677.atom
请问问题出在哪里呢？

**Comment by yefoenix** [comment]
错误信息显示什么呢？
其他阅读器能订阅吗？

**Comment by ChchNiu** [comment]
我是用W3C的Feed Validation service检查了一下。
返回结果如下所示：
It looks like this is a web page, not a feed. I looked for a feed associated with this page, but couldn't find one. Please enter the address of your feed to validate.
后来我换成Inoreader订阅器是可以的，但Readwise Reader还是不行。
感谢大佬的建议！
