### ISSUE TITLE
刚试了下，在群晖还是再hugging face上，添加账号都提示Request failed with status code 500

### ISSUE THREAD

**Issue by coolcoolron** [cooderl/wewe-rss#80]

**Comment by coolcoolron** [comment]
hugging face 提示[Nest] 70  - 03/14/2024, 2:18:32 PM     LOG [TrpcService] error: 
[Nest] 70  - 03/14/2024, 2:18:32 PM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 70  - 03/14/2024, 2:18:38 PM     LOG [TrpcService] error: 
[Nest] 70  - 03/14/2024, 2:18:38 PM     LOG [TrpcService] AxiosError: Request failed with status code 500
[Nest] 70  - 03/14/2024, 2:19:54 PM     LOG [TrpcService] error: 
[Nest] 70  - 03/14/2024, 2:19:54 PM     LOG [TrpcService] AxiosError: Request failed with status code 500

**Comment by nevertoday** [comment]
我也是500错误，不能再用了~

**Comment by nevertoday** [comment]
新版本这个问题

**Comment by stupidjoey** [comment]
同问题

**Comment by xingchen-zh** [comment]
应该是微信读书把这个接口封了吧

**Comment by HiMenma** [comment]
+1

**Comment by lhfly5201314** [comment]
哎，可惜了，这么好的项目，微信读书TM的玩不起啊😂

**Comment by Deja-vuuu** [comment]
<img width="411" alt="image" src="https://github.com/cooderl/wewe-rss/assets/27748682/64818ab2-9d49-44cf-b4d0-8daa65e6e974">
用不了了~

**Comment by Chivier** [comment]
同，不能添加用户了

**Comment by ChchNiu** [comment]
+1

**Comment by sevenday** [comment]
我也是用不了了，是不是被微信封了？

**Comment by buertang** [comment]
+1

**Comment by tang2554** [comment]
+1

**Comment by KeithW0726** [comment]
+1

**Comment by wklesss** [comment]
+1

**Comment by frankieyue96** [comment]
+1

**Comment by KeithW0726** [comment]
是不是可以给这个项目烧香了？腾讯真的狗

**Comment by johanlin** [comment]
+1, 希望能更新绕过去

**Comment by cooderzeng** [comment]
恢复了。

**Comment by cooderl** [comment]
兄弟们现在修复了。
如果有小黑屋的账号，重启一下服务or容器就可以了

**Comment by nevertoday** [comment]
虽然，但是：：：：还是容易出问题，隔天重新扫码之后，居然无法添加帐号， 也不报错， 状态假死。
