### ISSUE TITLE
频繁小黑屋，单微信读书里却正常获取

### ISSUE THREAD

**Issue by zymshirley** [cooderl/wewe-rss#86]
太容易小黑屋了
我甚至连一个公众号都没有添加就小黑屋了，更别说更新

无法自动更新的问题还没有解决
按照yml里设定应该是早上5点半和下午5点半更新，但从12号我手动更新到现在都没有更新过

**Comment by bosconb** [comment]
俺也一样，从12号就基本处于小黑屋状态，再也没有更新过。
![image](https://github.com/cooderl/wewe-rss/assets/47100031/2a8a1141-c9dd-471d-9fee-852404d7b112)

**Comment by worldyouwyl** [comment]
要重启一下docker

**Comment by Teda9** [comment]
same issue +1

**Comment by xingchen-zh** [comment]
同样,估计是大家访问量太大了,都用了同一个接口

**Comment by Ohhu** [comment]
same issue.

**Comment by ApusYe** [comment]
Same issue.

**Comment by William-Hunter** [comment]
same issue.

**Comment by chejg** [comment]
一直小黑屋，只能禁用

**Comment by xung** [comment]
一样小黑屋, 按readme中建议, 重启了dockcer服务. 还是同步不了, 报401错误, 然后账号状态又是小黑屋了

**Comment by Ohhu** [comment]
> same issue.

更新2.0版本后，自动更新正常了

建议删除账号后再更新容器刷新账号状态

**Comment by cooderl** [comment]
更新2.x版本，使用更加稳定的微信接口 #96
