### ISSUE TITLE
是不是不能用了？

### ISSUE THREAD

**Issue by august-xu** [cooderl/wewe-rss#88]
是不是不能用了，就添加当天用了一下，从第二天开始天天小黑屋？

**Comment by bosconb** [comment]
> 俺也一样

+1

**Comment by zhyine** [comment]
一样，从 3 月 5 日开始一直处于小黑屋状态

**Comment by cooderl** [comment]
> 一样，从 3 月 5 日开始一直处于小黑屋状态

微信更新了一点东西。
删除账号，重启容易，再重新扫码登录看看

**Comment by cooderl** [comment]
服务器不知道为啥重启了，现在好了

**Comment by zhyine** [comment]
> > 一样，从 3 月 5 日开始一直处于小黑屋状态
> 
> 微信更新了一点东西。 删除账号，重启容易，再重新扫码登录看看

感谢，已经解决了
