### ISSUE TITLE
无法添加账号，提示502

### ISSUE THREAD

**Issue by iar** [cooderl/wewe-rss#89]
添加微信读书账号出现502错误提示
![image](https://github.com/cooderl/wewe-rss/assets/3294506/263f877c-eae9-4805-a586-e45b5d71827b)

**Comment by Ohhu** [comment]
same issue.

**Comment by Hello-RXM** [comment]
同样的问题

**Comment by YoghurtGuy** [comment]
same issue

**Comment by ApusYe** [comment]
Same issue.

**Comment by cooderl** [comment]
服务器重启了，不晓得为啥，这个oracle背锅。现在可以再试试
