### ISSUE TITLE
最新版本报错 2.2.0     Unexpected token '<', "<html> <h"... is not valid JSON

### ISSUE THREAD

**Issue by rational-stars** [cooderl/wewe-rss#98]
Unexpected token '<', "<html> <h"... is not valid JSON

<img width="1162" alt="image" src="https://github.com/cooderl/wewe-rss/assets/65513250/4b6f273b-1f98-469e-8d1d-b46e6672fbc3">

**Comment by cooderl** [comment]
是点了更新全部？

**Comment by rational-stars** [comment]
是的  点了更新全部出现的

**Comment by rational-stars** [comment]
> 是点了更新全部？

是的

**Comment by veesong** [comment]
2.1.0 单个更新也报这个错

**Comment by YJL12345** [comment]
我的提示不知道是不是这个,但是我把微信账号删掉,重新授权解决了,现在不敢加太多rss了,一次加6个.

**Comment by rational-stars** [comment]
> 我的提示不知道是不是这个,但是我把微信账号删掉,重新授权解决了,现在不敢加太多rss了,一次加6个.

没有用 还是这样 我一共 11 个

**Comment by nevertoday** [comment]
我也是这个错误哈， 看来任重道远哈

**Comment by veesong** [comment]
今天早上发现正常了

**Comment by cooderl** [comment]
v2.2.3修复

**Comment by rational-stars** [comment]
> v2.2.3修复

![image](https://github.com/cooderl/wewe-rss/assets/65513250/16fcf60a-9af0-43dd-98a2-ca75e74a50fd)
<img width="808" alt="image" src="https://github.com/cooderl/wewe-rss/assets/65513250/b0e74f39-8087-4cfd-ac8c-fcd30609eb23">
<img width="2764" alt="image" src="https://github.com/cooderl/wewe-rss/assets/65513250/30f42ea0-20c6-47cd-9340-16287ef63768">
点击“更新全部” 按钮报的错
我是 rm 删除之后 拉的最新版本  还是这样  辛苦看下咯
